baseURL = "/"
publishDir="docs/"
languageCode = "es-es"
title = "Datasketch Dev"
theme = "hugo-titi"
themesDir = "themes"
googleAnalytics = "UA-164320300-2"

[params]
  [params.social]
    facebook = "https://facebook.com/datasketch/"
    twitter = "https://twitter.com/datasketch"
    email = "info@datasketch.co"
    always_visible = true

  [params.header]
    logo = "images/datasketch.svg"
    bg_color = "#fcfcfc"
    text_color = "#222526"
    bg_color_class = "bg-gray-800"
    text_color_class = ""
    # One of
    # sticky: always sticky on top
    # normal: static positioned
    # mixed: sticky after first child element of #content is offscreen
    behavior = "sticky"

  [params.footer]
    # The path inside the static folder
    # Note there is no leading nor trailing slash
    logo = "images/datasketch_v.svg"
    share_text = "Share"
    license_text = 'If you use or adapt the contents of this site please include a reference. All contents, unless otherwise stated is licenced with '
    license_link = 'https://creativecommons.org/licenses/by-sa/4.0/'
    license_link_text = 'CC-BY-SA'
    bg_color = "#222526"
    text_color = "#ffffff"
    bg_color_class = "bg-gray-900"
    text_color_class = "text-white"

  [[params.fonts]]
    family = "IBM Plex Sans"
    weight = [400, 500]

